### ISSUE TITLE
Release version?

### ISSUE THREAD

**Issue by regexident** [g-Off/Pathspec#1]
Hi Geoffrey,

is there any chance to get a tag release for Pathspec (e.g. `0.1.0`)?
I'd like to use it in a package and avoid future breakage.

(Preferably after merging https://github.com/g-Off/Pathspec/pull/2)

Thanks!

**Comment by g-Off** [comment]
Merged and tagged. Thanks again for the PR!

**Comment by regexident** [comment]
Thanks, @g-Off!
